name: add tag when pull request is merged

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: extract-version
        run: echo "version_in_manifest=$(sh scripts/get-manifest-version.sh)" >> $GITHUB_ENV

      - name: test-output
        run: echo ${{ env.version_in_manifest }}

      - name: print-context
        run: echo "github context ${{ toJson(github) }}"

      - name: print-comments
        run: 'curl -L -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" ${{ github.event.pull_request._links.comments.href }}'

    # - uses: rickstaa/action-create-tag@v1
    #     id: "create_tag"
    #     with:
    #       tag: ${{ env.version_in_manifest }}
    #       tag_exists_error: false
    #       message: "Latest release"
